//NOTE: This list is ordered inversely by week. For example, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21] would become [15,16,17,18,19,20,21,8,9,10,11,12,13,14,1,2,3,4,5,6,7].
data = [
    [[2025, 8, 31], 5, "Awake: 10:00 AM to 10:20 PM, no shower, no exercise", "I'm not gonna sugarcoat it: nothing of value actually happened today. More stuff will happen tomorrow for sure, but for now, this will be the shortest description."],
    [[2025, 9, 1], 4, "Awake: 8:00 AM to 10:10 PM, no shower, no exercise", "I really wanted to do a lot today, but I ended up just not. I thought about doing homework around 11:00 AM, but it ended up causing a negative reaction that repelled me from doing any homework for the rest of the day (and is also the reason that today was a 4). Anyway, now that August is over, it's time to really begin..."],
    [[2025, 9, 2], 3, "Awake: 6:00 AM to 9:40 PM, no shower, no exercise", "Dude, again? Today was basically a repeat of August 29, 2025, with nearly every class having an issue AGAIN... This is getting genuinely annoying. I just hope it'll get better from here... At least things got better when I got home."],
    [[2025, 9, 3], -1, "", ""],
    [[2025, 9, 4], -1, "", ""],
    [[2025, 9, 5], -1, "", ""],
    [[2025, 9, 6], -1, "", ""],
    [[2025, 8, 24], 6, "Awake: 12:00 AM to 1:20 AM, no shower, no exercise", "The first day!\nWorked on Omnincremental quite a lot, improved the home page, but most importantly, this page exists now! This is because this is the week that high school begins for me.\nOther than that, I finished up my annoying Math summer homework (finally), and am aiming to complete the LA stuff tomorrow. Overall, a pretty good day; I don't know whether to put this in 6/10 or 7/10 but I'm leaning towards 6/10 due to today being pretty uneventful (of course, it was still good, though)."],
    [[2025, 8, 25], 5, "Awake: 10:00 AM to 4:00 PM + 8:00 PM to 1:00 AM, no shower, no exercise", "The second day!\nI was about as productive in homework as I was yesterday, completing nearly all of the LA homework I had promised to complete. Other than that, today's 6/10 productivity is cancelled by the 4/10 rest of the day, with me doing nothing, as well as taking a 4 hour nap in the middle. Tomorrow is the final day before high school begins, so let's hope it's a good one! (actually it will probably just be another 5/10)"],
    [[2025, 8, 26], 5, "Awake: 1:30 PM to 10:00 PM, no shower, no exercise", "The thir-ok I'll stop now. But for real, today is the last day before high school, and it's kinda crazy... Also, I guess I was right about today being a 5/10 yesterday. Anyway, I fnished up the remaining portion of the LA homework just in time, and the rest of the day was basically nothing, so yeah. High school will make things more interesting, though..."],
    [[2025, 8, 27], 5, "Awake: 6:00 AM to 8:20 PM, showered, no exercise", "It has begun.\n\nBut seriously, today was the first day of high school, and it felt relatively surreal (as to be expected...). I won't go into too much detail here, but it being the first day doesn't give it any bonus points. However, high school could go into any direction from here, and that thought was stuck in my head for the whole day. The reason I went to bed so early was because I was just genuinely tired, not to catch up on sleep."],
    [[2025, 8, 28], 4, "Awake: 6:20 AM to 10:30 PM, no shower, no exercise", "A bit worse than yesterday, but still alright. The reason this is 4/10 is because of an awkward moment that happened in Spanish class. Other than that, there's not much to elaborate on, unfortunately. I didn't really do much today other than idle on Youtube, so this is going to have to be the end of the description."],
    [[2025, 8, 29], 3, "Awake: 6:00 AM to 11:00 PM, no shower, no exercise", "Ok, this isn't fun anymore. Nearly every class had something wrong happen. Would be 2/10 if things didn't get better at home, and also it's Friday, so it's time for the first weekend of high school! But anyway, the reason the school day was bad today was mainly because of 2 things: the work is getting obscenely difficult for just the 3rd day of school, and I sometimes just lose my ability to talk when I'm asked questions. I was also really tired, which could've contributed. But yeah, that's it, hopefully tomorrow is better."],
    [[2025, 8, 30], 6, "Awake: 9:00 AM to 1:00 AM, no shower, no exercise", "It was looking normal at first, but then a bunch of banger videos dropped, and then I did my Math homework on top of that! Definitely a good day, but nothing much else happened, so it's just going to be a 6/10. Still much better than yesterday for sure."],
];
